[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version_provider = "commitizen"
version_files = ["VERSION"]
update_changelog_on_bump = true
major_version_zero = true
version = "0.9.1"
